name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.NASA_API_KEY }}

      - name: Run NASA Negative Tests with Postman CLI
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/NASA_Negative_Tests.json" \
            -e "29142931-df967d1f-7ccb-47c4-94b4-f03eb8f599dd" \
            --integration-id "your_integration_id" \
            --reporter-cli-no-banner

      - name: Run NASA Positive Tests with Postman CLI
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/NASA_Positive_Tests.json" \
            -e "29142931-df967d1f-7ccb-47c4-94b4-f03eb8f599dd" \
            --integration-id "your_integration_id" \
            --reporter-cli-no-banner
